package TLA.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class IDAndPostfixOp_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.ID$9dL0));
    tgs.append(" ");
    tgs.append(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.PostfixOp$9dLY).getPresentation());
    tgs.append(" ");
  }

  private static final class PROPS {
    /*package*/ static final SProperty ID$9dL0 = MetaAdapterFactory.getProperty(0x7a6b8f83d2024e59L, 0x94ecf562edfca98dL, 0x467903da84aac8a8L, 0x467903da84aac8a9L, "ID");
    /*package*/ static final SProperty PostfixOp$9dLY = MetaAdapterFactory.getProperty(0x7a6b8f83d2024e59L, 0x94ecf562edfca98dL, 0x467903da84aac8a8L, 0x467903da84aac8abL, "PostfixOp");
  }
}
