package TLA.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TupleForChoose_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("〈");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.IDList$2JW0));
    tgs.append("〉");
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.ExprOption$dC7d) != null)) {
      tgs.append(" ∈ ");
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.ExprOption$dC7d));
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink IDList$2JW0 = MetaAdapterFactory.getContainmentLink(0x7a6b8f83d2024e59L, 0x94ecf562edfca98dL, 0x7551f37ec111f722L, 0x7551f37ec111f723L, "IDList");
    /*package*/ static final SContainmentLink ExprOption$dC7d = MetaAdapterFactory.getContainmentLink(0x7a6b8f83d2024e59L, 0x94ecf562edfca98dL, 0x7551f37ec111f722L, 0x70c5d7f04f50eabfL, "ExprOption");
  }
}
