package Paster.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class EditorPopup_paste_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "Paster.plugin.EditorPopup_paste_ActionGroup";

  public EditorPopup_paste_ActionGroup(@Nullable ApplicationPlugin plugin) {
    super("EditorPopup_paste", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    EditorPopup_paste_ActionGroup.this.addAction("Paster.plugin.PasteAsAntlrRules_Action");
  }
}
