package Paster.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconLoadingUtil;

public class IconContainer {
  protected static Icon ICON_a0 = IconLoadingUtil.loadIcon("MPS16.png", IconContainer.class);
}
