package TLA.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_WForSFEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_WForSFEnum() {
    super(0x7a6b8f83d2024e59L, 0x94ecf562edfca98dL, 0x6dd00814ec11c1f6L, "WForSFEnum", "r:3f6b7621-97d8-464c-bb3b-fdae13d84a79(TLA.structure)/7912833431242916342");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_WF_0 = new EnumerationDescriptor.MemberDescriptor("WF", "WF", 0x6dd00814ec11c1f7L, "r:3f6b7621-97d8-464c-bb3b-fdae13d84a79(TLA.structure)/7912833431242916343");
  private final EnumerationDescriptor.MemberDescriptor myMember_SF_0 = new EnumerationDescriptor.MemberDescriptor("SF", "SF", 0x6dd00814ec11c1f8L, "r:3f6b7621-97d8-464c-bb3b-fdae13d84a79(TLA.structure)/7912833431242916344");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x7a6b8f83d2024e59L, 0x94ecf562edfca98dL, 0x6dd00814ec11c1f6L, 0x6dd00814ec11c1f7L, 0x6dd00814ec11c1f8L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_WF_0, myMember_SF_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "WF":
        return myMember_WF_0;
      case "SF":
        return myMember_SF_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
